name: Trigger VPM Repos Update

on:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger hrpnx/vpm-repos Build Repo Listing
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.VPM_REPOS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hrpnx/vpm-repos/dispatches \
            -d '{"event_type":"update-listing","client_payload":{"repository":"${{ github.repository }}","version":"${{ github.event.release.tag_name }}"}}'
